<?php

namespace App\Services\Subscriptions;

use App\Jobs\Schedule\BillSubscriptionJob;
use App\Services\BaseService;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class BillingService extends BaseService
{
    public function __construct(public ?Carbon $billingAt)
    {
        $this->billingAt ??= now();
    }

    public function __invoke()
    {
        $billingAt = $billingAt ?? now();
        $billableSubscriptions = $this->getBillableSubscriptions($billingAt);

        $groupedSubscriptions = $billableSubscriptions->groupBy('customer_id');

        logger()->info(logname(), [
            'billing_at' => $billingAt,
            'subscriptions_count' => $groupedSubscriptions
                ->flatMap(fn($subscriptions) => $subscriptions->pluck('id'))
                ->count(),
        ]);

        foreach ($groupedSubscriptions as $customerId => $customerSubscriptions) {
            $billingSubscriptions = [];

            foreach ($customerSubscriptions as $subscription) {
                $nextSubscription = $this->getNextSubscription($subscription->id);

                if ($nextSubscription && $nextSubscription->current_state === 'pending') {
                    // In case of downgrade, terminate the current subscription
//                    TerminateSubscriptionJob::dispatch($subscription, $billingAt->timestamp);
                } else {
                    $billingSubscriptions[] = $subscription;
                }
            }

            if (!empty($billingSubscriptions)) {
                BillSubscriptionJob::dispatch(
                    collect($billingSubscriptions),
                    $billingAt,
                    'subscription_periodic',
                );

//                BillNonInvoiceableFeesJob::dispatch($billingSubscriptions, $billingAt);
            }
        }
    }

    private function getNextSubscription($subscriptionId)
    {
        return DB::table('billing_subscriptions')
            ->where('previous_subscription_id', $subscriptionId)
            ->first();
    }

    public function getBillableSubscriptions(Carbon $billingAt)
    {
        $a = DB::table('billing_subscriptions')
            ->join('account_customers', 'account_customers.id', '=', 'billing_subscriptions.customer_id')
            ->join('mgmt_organizations', 'mgmt_organizations.id', '=', 'account_customers.organization_id')
            ->join('pricing_plans', 'pricing_plans.id', '=', 'billing_subscriptions.plan_id')
            ->whereRaw($this->getBillableSubscriptionsCondition($billingAt))
            ->select('billing_subscriptions.*');

        $a = $a->distinct()
            ->get();

        return $a;
    }

    private function getBillableSubscriptionsCondition(Carbon $billingAt)
    {
        $a = "(" . implode(") OR (", [
                $this->monthlyAnniversary(),
                $this->yearlyAnniversary(),
                $this->yearlyWithMonthlyChargesAnniversary($billingAt),
            ]) . ")";

        return $a;
    }

    private function monthlyAnniversary(): string
    {
        return "
            pricing_plans.billing_anchor = 'anniversary'
            AND pricing_plans.renew_interval = 'P1M'
            AND (
                DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)) =
                IF(
                    DAY(LAST_DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))) =
                    DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone)),
                    DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)),
                    DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))
                )
            )
        ";
    }

    // Yearly plans invoiced on anniversary
    // generated by stripe

    private function yearlyAnniversary(): string
    {
        return "
            pricing_plans.billing_anchor = 'anniversary'
            AND pricing_plans.renew_interval = 'P1Y'
            AND MONTH(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)) =
                MONTH(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))
            AND (
                DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)) =
                IF(
                    MONTH(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone)) = 2
                    AND DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone)) = 28
                    AND DAY(LAST_DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))) = 28,
                    DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)),
                    DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))
                )
            )
        ";
    }

    // generated by Plandalf
    // Yearly plans with monthly charges invoiced on anniversary
    private function yearlyWithMonthlyChargesAnniversary(Carbon $billingAt): string
    {
        return "
            pricing_plans.billing_anchor = 'anniversary'
            AND pricing_plans.renew_interval = 'P1Y'
            AND pricing_plans.invoice_interval = 'P1M'
            AND (
                DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)) =
                IF(
                    DAY(LAST_DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))) =
                    DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone)),
                    DAY(CONVERT_TZ(billing_subscriptions.start_at, '+00:00', mgmt_organizations.timezone)),
                    DAY(CONVERT_TZ(NOW(), '+00:00', mgmt_organizations.timezone))
                )
            )
        ";
    }
}
