error_log = /dev/stderr
log_level = notice ; switch to warning when working
daemonize = no
log_limit = 8192

[www]
listen = 9000
clear_env = no

pm = dynamic
pm.max_children = 6
pm.start_servers = 3
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500
pm.process_idle_timeout = 10s

access.log = /dev/null
slowlog = /dev/stderr
request_slowlog_timeout = 2s
catch_workers_output = yes
decorate_workers_output = no
request_terminate_timeout = 10s
security.limit_extensions = .php
php_flag[display_errors] = off
php_admin_value[error_log] = /dev/stderr
php_admin_flag[log_errors] = on
php_admin_value[memory_limit] = 256M
