display_errors=0
include_path = ".:/usr/share/php83"
memory_limit=256M
curl.cainfo="/etc/ssl/cert.pem"
openssl.cafile="/etc/ssl/cert.pem"
log_errors_max_len = 8192
zend.exception_ignore_args=Off
expose_php=off
extension_dir=/usr/lib/php83/modules/

